# Generated by Django 6.1 on 2026-08-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount charged to customer (INR)', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='GST/tax amount (INR)', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cooperative platform fee (INR)', max_digits=10)),
                ('worker_payout', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid to the worker (INR)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, default='', help_text='Razorpay order ID', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', help_text='Razorpay payment ID (set after successful payment)', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', help_text='Razorpay payment signature for verification', max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid to worker (INR)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, default='', help_text='Bank/UPI transaction reference number', max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_payouts', to='payments.invoice')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Payout',
                'verbose_name_plural': 'Worker Payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
