# Generated by Django 6.1 on 2026-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the cooperative society', max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Official cooperative registration number', max_length=50, null=True, unique=True)),
                ('region', models.CharField(help_text='Geographic region / area served', max_length=200)),
                ('district', models.CharField(blank=True, default='', help_text='District name', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State name', max_length=100)),
                ('federation_level', models.CharField(choices=[('village', 'Village Level'), ('district', 'District Level'), ('state', 'State Level')], default='village', help_text='Level in the cooperative federation hierarchy', max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', help_text='Primary contact person for this cooperative', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=15)),
                ('established_date', models.DateField(blank=True, help_text='Date the cooperative was established', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cooperative is currently active')),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
                'ordering': ['name'],
            },
        ),
    ]
