# Generated by Django 6.1 on 2026-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='federation_level',
            field=models.CharField(choices=[('village', 'Village Level'), ('district', 'District Level'), ('state', 'State Level')], default='village', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('region', models.CharField(help_text='Region/area for forecast', max_length=200)),
                ('service_category', models.CharField(choices=[('cleaning', 'Home Cleaning'), ('plumbing', 'Plumbing Repair'), ('electrical', 'Electrical Work'), ('carpentry', 'Carpentry & Woodwork'), ('cooking', 'Cooking & Tiffin'), ('elderly_care', 'Elderly Care'), ('gardening', 'Gardening & Landscaping'), ('painting', 'Painting Services')], max_length=50)),
                ('forecast_date', models.DateField(help_text='Date of predicted demand')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week')),
                ('predicted_demand', models.PositiveIntegerField(help_text='Predicted number of bookings')),
                ('recommended_worker_count', models.PositiveIntegerField(default=0, help_text='Recommended available workers for this demand')),
                ('actual_demand', models.PositiveIntegerField(blank=True, help_text='Actual number of bookings (filled in later for accuracy tracking)', null=True)),
                ('is_shortage', models.BooleanField(default=False, help_text='Whether predicted demand exceeds available workers')),
                ('model_version', models.CharField(default='v1.0', help_text='Version of the forecasting model used', max_length=50)),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['forecast_date', 'service_category'],
                'unique_together': {('region', 'service_category', 'forecast_date')},
            },
        ),
    ]
