"""Cooperative Admin app — Models for cooperatives, federation, and demand forecasting."""

from django.db import models
from core.models import TimeStampedModel


class Cooperative(TimeStampedModel):
    """Represents a cooperative society in the federation hierarchy."""

    FEDERATION_LEVEL_CHOICES = [
        ('village', 'Village Level'),
        ('district', 'District Level'),
        ('state', 'State Level'),
    ]

    name = models.CharField(max_length=200)
    registration_number = models.CharField(max_length=50, unique=True, blank=True, null=True)
    region = models.CharField(max_length=200)
    district = models.CharField(max_length=100, blank=True, default='')
    state = models.CharField(max_length=100, blank=True, default='')
    federation_level = models.CharField(max_length=20, choices=FEDERATION_LEVEL_CHOICES, default='village')
    contact_person = models.CharField(max_length=200, blank=True, default='')
    contact_phone = models.CharField(max_length=15, blank=True, default='')
    established_date = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Cooperative'
        verbose_name_plural = 'Cooperatives'
        ordering = ['name']

    def __str__(self):
        return f"{self.name} ({self.get_federation_level_display()})"

    @property
    def worker_count(self):
        from workers.models import WorkerProfile
        return WorkerProfile.objects.filter(cooperative=self, user__is_active=True).count()


class DemandForecast(TimeStampedModel):
    """
    AI-based demand forecasting results.
    Stores predicted demand for each service category, region, and date.
    Generated by Celery periodic task (daily).
    """

    SERVICE_CHOICES = [
        ('cleaning', 'Home Cleaning'),
        ('plumbing', 'Plumbing Repair'),
        ('electrical', 'Electrical Work'),
        ('carpentry', 'Carpentry & Woodwork'),
        ('cooking', 'Cooking & Tiffin'),
        ('elderly_care', 'Elderly Care'),
        ('gardening', 'Gardening & Landscaping'),
        ('painting', 'Painting Services'),
    ]

    DAY_CHOICES = [
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
        (6, 'Sunday'),
    ]

    region = models.CharField(max_length=200, help_text="Region/area for forecast")
    service_category = models.CharField(max_length=50, choices=SERVICE_CHOICES)
    forecast_date = models.DateField(help_text="Date of predicted demand")
    day_of_week = models.IntegerField(choices=DAY_CHOICES, help_text="Day of week")
    predicted_demand = models.PositiveIntegerField(help_text="Predicted number of bookings")
    recommended_worker_count = models.PositiveIntegerField(
        help_text="Recommended available workers for this demand",
        default=0
    )
    actual_demand = models.PositiveIntegerField(
        blank=True, null=True,
        help_text="Actual number of bookings (filled in later for accuracy tracking)"
    )
    is_shortage = models.BooleanField(
        default=False,
        help_text="Whether predicted demand exceeds available workers"
    )
    model_version = models.CharField(
        max_length=50, default='v1.0',
        help_text="Version of the forecasting model used"
    )

    class Meta:
        verbose_name = 'Demand Forecast'
        verbose_name_plural = 'Demand Forecasts'
        ordering = ['forecast_date', 'service_category']
        unique_together = ['region', 'service_category', 'forecast_date']

    def __str__(self):
        return (
            f"{self.get_service_category_display()} in {self.region} — "
            f"{self.forecast_date}: {self.predicted_demand} bookings"
        )
