# Generated by Django 6.1 on 2026-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male / पुरुष'), ('female', 'Female / महिला'), ('other', 'Other / अन्य')], help_text='Gender identity', max_length=10, null=True),
        ),
    ]
