# Generated by Django 6.1 on 2026-08-27 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.TextField(help_text="Customer's description of the service needed")),
                ('scheduled_datetime', models.DateTimeField(help_text='When the customer wants the service')),
                ('is_emergency', models.BooleanField(default=False, help_text='Emergency bookings auto-match to nearest worker ASAP')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_worker', 'Cancelled by Worker'), ('disputed', 'Disputed')], default='pending', max_length=30)),
                ('address_text', models.TextField(blank=True, default='', help_text='Text address for the service location')),
                ('latitude', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Estimated price shown to customer (INR)', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, help_text='Final price after service completion (INR)', max_digits=10)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, help_text='Worker assigned to this booking (set after matching)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_worker', 'Cancelled by Worker'), ('disputed', 'Disputed')], max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about the status change')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who triggered the status change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class name or emoji', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Base/starting price for this service category (INR)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('related_skills', models.ManyToManyField(blank=True, help_text='Skills required for this service category', related_name='service_categories', to='workers.skill')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service_category',
            field=models.ForeignKey(help_text='Type of service requested', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.servicecategory'),
        ),
    ]
