# Generated by Django 6.1 on 2026-08-27 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperative_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class name (e.g., for Font Awesome or emoji)', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='workers.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('bio', models.TextField(blank=True, default='', help_text='Short bio / description of services offered')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', help_text='Current availability status', max_length=20)),
                ('current_latitude', models.FloatField(default=0.0, help_text='Current latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('current_longitude', models.FloatField(default=0.0, help_text='Current longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text="Whether the worker's documents have been verified by cooperative admin")),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('id_proof_type', models.CharField(blank=True, default='', help_text='Type of ID proof (Aadhaar, PAN, Voter ID, etc.)', max_length=50)),
                ('id_proof_file', models.FileField(blank=True, help_text='Upload ID proof document', null=True, upload_to='documents/id/')),
                ('bank_account_number', models.CharField(blank=True, default='', help_text='Bank account number for payouts', max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, default='', help_text='IFSC code for bank transfers', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Name of the bank', max_length=100)),
                ('upi_id', models.CharField(blank=True, default='', help_text='UPI ID for payments', max_length=50)),
                ('cooperative', models.ForeignKey(blank=True, help_text='The cooperative this worker belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='cooperative_admin.cooperative')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills this worker possesses', related_name='workers', to='workers.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'verbose_name_plural': 'Worker Profiles',
                'ordering': ['-avg_rating', '-total_jobs_completed'],
            },
        ),
        migrations.CreateModel(
            name='WorkerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('policy_number', models.CharField(help_text='Insurance policy number', max_length=50, unique=True)),
                ('provider', models.CharField(help_text='Insurance provider name', max_length=200)),
                ('coverage_type', models.CharField(choices=[('accident', 'Accident Cover'), ('health', 'Health Cover'), ('life', 'Life Insurance'), ('combined', 'Combined Cover')], help_text='Type of insurance coverage', max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, default=0, help_text='Coverage amount in INR', max_digits=12)),
                ('valid_from', models.DateField(help_text='Insurance validity start date')),
                ('valid_till', models.DateField(help_text='Insurance validity end date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Activation'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_insurances', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Insurance',
                'verbose_name_plural': 'Worker Insurances',
                'ordering': ['-valid_till'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('certificate_file', models.FileField(help_text='Upload certificate document', upload_to='documents/certificates/')),
                ('certificate_name', models.CharField(help_text='Name/title of the certification', max_length=200)),
                ('issued_by', models.CharField(blank=True, default='', help_text='Organization that issued the certification', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by cooperative admin')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(help_text='Skill this certification is for', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='workers.skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
    ]
