# Generated by Django 6.1 on 2026-08-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking_request', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_completed', 'Booking Completed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('review_received', 'New Review'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('insurance_update', 'Insurance Update'), ('system', 'System Notification')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
